(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(s){if(s.ep)return;s.ep=!0;const r=o(s);fetch(s.href,r)}})();const a={taskForm:document.querySelector("#task-form"),taskList:document.querySelector("#task-list"),themeButton:document.querySelector("#themeToggle")};function m(e,t){return{id:Date.now(),name:e,description:t}}function c(e,t){const o=JSON.stringify(t);localStorage.setItem(e,o)}function d(e){const t=localStorage.getItem(e);return t?JSON.parse(t):null}function u(e){return`
    <li class="task-list-item">
    <button class="task-list-item-btn" data-id="${e.id}">Delete</button>
    <h3>${e.name}</h3>
    <p>${e.description}</p>
</li>

    `}function f(e){return e.map(t=>u(t)).join("")}let n=[];function k(){d("theme")==="light"?(document.body.classList.remove("theme-dark"),document.body.classList.add("theme-light")):(document.body.classList.remove("theme-light"),document.body.classList.add("theme-dark"));const t=d("tasks");if(t){n=t;const o=f(n);a.taskList.innerHTML=o}else a.taskList.innerHTML=""}k();//!!!!!   Конец кода по createTaskMarkup, renderTaskList
function h(e){e.preventDefault();const t=e.currentTarget.elements.taskName.value.trim(),o=e.currentTarget.elements.taskDescription.value.trim();if(t===""||o===""){alert("Будь-ласка заповніть пусті поля!");return}const i=m(t,o),s=u(i);a.taskList.insertAdjacentHTML("beforeend",s),console.log(i),n.push(i),c("tasks",n),e.currentTarget.reset()}a.taskForm.addEventListener("submit",h);function g(e){if(!e.target.classList.contains("task-list-item-btn"))return;console.log("Кликнули по кнопке Delete!");const t=Number(e.target.dataset.id);n=n.filter(i=>i.id!==t),c("tasks",n),e.target.closest(".task-list-item").remove()}a.taskList.addEventListener("click",g);function p(){document.body.classList.contains("theme-dark")?(document.body.classList.replace("theme-dark","theme-light"),c("theme","light")):(document.body.classList.replace("theme-light","theme-dark"),c("theme","dark"))}a.themeButton.addEventListener("click",p);
//# sourceMappingURL=index.js.map
