(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function o(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(s){if(s.ep)return;s.ep=!0;const r=o(s);fetch(s.href,r)}})();const c={taskForm:document.querySelector("#task-form"),taskList:document.querySelector("#task-list"),themeButton:document.querySelector("#themeToggle")};function f(e,t){return{id:Date.now(),name:e,description:t}}function l(e,t){const o=JSON.stringify(t);localStorage.setItem(e,o)}function u(e){const t=localStorage.getItem(e);return t?JSON.parse(t):null}function m(e){return`
    <li class="task-list-item">
    <button class="task-list-item-btn" data-id="${e.id}">Delete</button>
    <h3>${e.name}</h3>
    <p>${e.description}</p>
</li>

    `}function k(e){return e.map(t=>m(t)).join("")}i;let a=[];function h(){u("theme")==="light"?(document.body.classList.remove("theme-dark"),document.body.classList.add("theme-light")):(document.body.classList.remove("theme-light"),document.body.classList.add("theme-dark"));const t=u("tasks");if(t){a=t;const o=k(a);c.taskList.innerHTML=o}else c.taskList.innerHTML=""}h();//!!!!!   Конец кода по createTaskMarkup, renderTaskList
function g(e){e.preventDefault();const t=e.currentTarget.elements.taskName.value.trim(),o=e.currentTarget.elements.taskDescription.value.trim();if(t===""||o===""){alert("Будь-ласка заповніть пусті поля!");return}const n=f(t,o),s=m(n);c.taskList.insertAdjacentHTML("beforeend",s),console.log(n),a.push(n),l("tasks",a),e.currentTarget.reset()}c.taskForm.addEventListener("submit",g);function p(e){if(!e.target.classList.contains("task-list-item-btn"))return;console.log("Кликнули по кнопке Delete!");const t=Number(e.target.dataset.id);a=a.filter(n=>n.id!==t),l("tasks",a),e.target.closest(".task-list-item").remove()}c.taskList.addEventListener("click",p);function L(){document.body.classList.contains("theme-dark")?(document.body.classList.replace("theme-dark","theme-light"),l("theme","light")):(document.body.classList.replace("theme-light","theme-dark"),l("theme","dark"))}c.themeButton.addEventListener("click",L);
//# sourceMappingURL=index.js.map
